# Generated by Django 6.0.6 on 2026-07-17 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_incomesource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='source',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Freelancing', 'Freelancing'), ('Pocket Money', 'Pocket Money'), ('Scholarship', 'Scholarship'), ('Investment', 'Investment'), ('Rental Income', 'Rental Income'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.UniqueConstraint(fields=('user', 'source'), name='unique_user_income_source'),
        ),
    ]
