# Generated by Django 6.0.6 on 2026-07-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_incomesource_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyIncome',
        ),
    ]
