# Generated by Django 6.0.6 on 2026-07-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_delete_monthlyincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.incomesource'),
        ),
    ]
