# Generated by Django 6.0.6 on 2026-07-21 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_transaction_paid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='date',
            field=models.DateField(default=datetime.date(2026, 7, 15)),
            preserve_default=False,
        ),
    ]
