# Generated by Django 6.0.6 on 2026-08-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_budget'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incomesource',
            name='unique_user_income_source',
        ),
    ]
